"""Report Agent - generates structured research reports."""
from datetime import datetime


class ReportAgent:
    """Agent specialized in generating structured research reports."""

    def generate(self, query: str, research: str, analysis: str) -> str:
        """Generate a structured research report.
        
        Args:
            query: Original research query
            research: Raw research findings
            analysis: Analysis results
            
        Returns:
            Formatted research report
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        report = f"""
{'='*60}
RESEARCH REPORT
{'='*60}

Generated: {timestamp}
Query: {query}

{'='*60}
EXECUTIVE SUMMARY
{'='*60}

{analysis}

{'='*60}
DETAILED FINDINGS
{'='*60}

{research}

{'='*60}
METHODOLOGY
{'='*60}

This report was generated by a multi-agent AI system:
1. Research Agent: Gathered information via web search and RAG
2. Analysis Agent: Extracted key points and generated summary
3. Report Agent: Compiled findings into structured report

Agent communication followed A2A (Agent-to-Agent) patterns
with structured message passing between specialized agents.

{'='*60}
END OF REPORT
{'='*60}
"""
        return report
